#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Test and documentation for yes/no prompt defaults."""

import sys
import io

# Set UTF-8 encoding for Windows console
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

print("=" * 70)
print("📋 YES/NO PROMPT DEFAULTS - DOCUMENTATION")
print("=" * 70)
print()
print("All yes/no prompts in the application now have smart defaults!")
print()

print("🎯 PROMPTS WITH [yes] DEFAULT")
print("-" * 70)
print()
print("These prompts accept Enter key to select YES:")
print()
print("1️⃣  Use this file? (yes/no) [yes]:")
print("   📍 Location: File Manager > Edit devices.csv/commands.txt")
print("   ✅ Press Enter → Uses the detected file")
print()
print("2️⃣  Enter enable mode? (yes/no) [yes]:")
print("   📍 Location: Main Menu > Run Collection")
print("   ✅ Press Enter → Enters enable mode")
print()

print("🛡️  PROMPTS WITH [no] DEFAULT")
print("-" * 70)
print()
print("These prompts accept Enter key to select NO (safe defaults):")
print()
print("1️⃣  Create this file? (yes/no) [no]:")
print("   📍 Location: File Manager > Browse for file (file not found)")
print("   ✅ Press Enter → Does NOT create file")
print()
print("2️⃣  Overwrite? (yes/no) [no]:")
print("   📍 Location: File Manager > Create sample files")
print("   ✅ Press Enter → Does NOT overwrite existing file")
print()
print("3️⃣  Reset all settings to defaults? (yes/no) [no]:")
print("   📍 Location: Settings Menu > Reset to Defaults")
print("   ✅ Press Enter → Does NOT reset settings")
print()

print("🔄 PROMPTS WITH [current] DEFAULT")
print("-" * 70)
print()
print("These prompts keep the current value when you press Enter:")
print()
print("1️⃣  Strip whitespace? (yes/no) [current]:")
print("   📍 Location: Settings Menu > Strip Whitespace")
print("   ✅ Press Enter → Keeps current setting")
print()
print("2️⃣  Enable session logging? (yes/no) [current]:")
print("   📍 Location: Settings Menu > Enable Session Logging")
print("   ✅ Press Enter → Keeps current setting")
print()
print("3️⃣  Enter enable mode on connect? (yes/no) [current]:")
print("   📍 Location: Settings Menu > Enable Mode")
print("   ✅ Press Enter → Keeps current setting")
print()
print("4️⃣  Retry on connection failure? (yes/no) [current]:")
print("   📍 Location: Settings Menu > Retry on Failure")
print("   ✅ Press Enter → Keeps current setting")
print()

print("=" * 70)
print("💡 USAGE TIPS")
print("=" * 70)
print()
print("✅ Press Enter to accept the default (shown in brackets)")
print("✅ Type 'yes' or 'y' to explicitly select yes")
print("✅ Type 'no' or 'n' to explicitly select no")
print()
print("🎯 Smart defaults mean:")
print("   • Less typing when the default is what you want")
print("   • Safe defaults for destructive actions (always [no])")
print("   • Convenient defaults for common actions (usually [yes])")
print("   • Settings preserve current values by default")
print()
print("=" * 70)
print("🎉 All prompts updated for better UX!")
