name: Code Formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Check Black formatting
        run: black --check --line-length=100 .
      - name: Check isort formatting
        run: isort --check --profile black --line-length 100 .
