name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body: |
            ## Installation

            ```bash
            pip install netmiko-collector
            ```

            Or install from source:

            ```bash
            git clone https://github.com/lammesen/netmiko-script.git
            cd netmiko-script
            pip install -r requirements.txt
            ```
